aliases:
  # Alternate command names that players can use to activate RTP.
  - "rtp"
  - "axrtp"

teleport:
  # Teleportation settings.
  maximum-attempts: 32 # Maximum number of attempts to find a safe location before giving up.
  teleport-on-first-join:
    # Teleport players to a random location on their first join (new players).
    enabled: false # Whether this feature is enabled.
    world: "world" # The world in which to teleport new players.
  cooldown:
    # Cooldown period between teleports.
    enabled: false # Whether the cooldown is enabled.
    time: 30 # Cooldown time in seconds.
    lock-after: 0 # 0 if disabled. If there is a time limit, specify the number of minutes to wait before the cooldown is lifted.
  delay:
    # Delay before teleporting.
    enabled: true # Whether the delay is enabled.
    time: 3 # Delay time in seconds.
    sound: "BLOCK_ANVIL_PLACE" # Sound to play during the delay.
    cancel-on-move: false # Whether to cancel the teleport if the player moves.
    title:
      # Title and subtitle to display during the delay.
      enabled: true # Whether to display the title.
      title: "&aTeleporting in" # Main title.
      subtitle: "&2{time}" # Subtitle, which displays the remaining time ( {time} is replaced with the remaining time).

blacklisted-blocks:
  # List of blocks to avoid when teleporting. Players will not be teleported into these blocks.
  # See more -> https://jd.papermc.io/paper/1.21.4/org/bukkit/Material.html
  - "WATER" # Water
  - "LAVA" # Lava
  - "CACTUS" # Cactus
  - "KELP" # Kelp (seaweed)

blacklisted-worlds:
  # List of worlds to avoid when teleporting.
  - "world_nether" # Nether world
  - "world_the_end" # The End world

title:
  # Title and subtitle to display after teleporting.
  enabled: true # Whether to display the title.
  title: "&aTeleported!" # Main title.
  subtitle: "&eGood luck exploring!" # Subtitle.

sound:
  # Sound effects to play after teleporting.
  enabled: true # Whether to play sound effects.
  list:
    # See more -> https://jd.papermc.io/paper/1.21.1/org/bukkit/Sound.html
    - "UI_BUTTON_CLICK" # List of sounds to play.

particle:
  # Particle effects to display when teleporting.
  enabled: true # Whether to display particle effects.
  display: "CRIT_MAGIC" # Type of particle effect to display.

effects:
  # Effects (e.g. status effects) to apply when teleporting.
  enabled: true # Whether to apply effects.
  list:
    # See more -> https://jd.papermc.io/paper/1.21.4/org/bukkit/potion/PotionEffectType.html
    - "BLINDNESS:3:1" # Blindness effect, lasting 5 seconds, with an amplifier of 1.
    - "SLOWNESS:3:1" # Slowness effect, lasting 5 seconds, with an amplifier of 1.

world-radius:
  # World-specific radius settings.
  world: 100 # Radius for the "world" world.
  world_nether: 1000 # Radius for the "world_nether" world.

commands-on-rtp:
  # Commands to run when the player's RTPd.
  enabled: true
  list:
    - "world: msg %player% you have just RTPd to world" # It automatically replaces %player% with the name of the player.
    - "world_nether: msg %player% nether"

blacklisted-biomes: # {biome}:{world's name}
  - "DESERT:world" # In this concept you won't be able to teleport in a forest biome in world.

prices:
  enabled: false # Requires VAULT PLUGIN!
  list: # {price}:{world's name}
    - "100:world" # To use other currencies you should use the currency plugin's take command to take it from the player! WITH commands-on-rtp setting!
    - "200:world_nether"

respect: # If a value is true like worldguard then the player won't be able to teleport into a protected region.
  worldguard: false

centers: []
